name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Build Docker Image
        uses: whoan/docker-build-with-cache-action@v5
        with:
          image_name: halvardssm/package-translation-fetch/translations
          dockerfile: .github/Dockerfile
          username: halvardssm
          password: "${{ secrets.GITHUB_TOKEN }}"
          registry: docker.pkg.github.com
          push_image_and_stages: false

      - name: Get contents of home folder
        run: docker run docker.pkg.github.com/halvardssm/package-translation-fetch/translations ls dist

      - name: Run Tests
        run: docker run docker.pkg.github.com/halvardssm/package-translation-fetch/translations yarn test -p ${{ secrets.PATH }} -r ${{ secrets.REPO }} -t ${{ secrets.TOKEN }}

  release:
    needs: test
    runs-on: ubuntu-latest
    if: contains(github.ref, 'master')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check version changes
        uses: EndBug/version-check@v1
        id: check

      - name: Version update detected
        if: steps.check.outputs.changed == 'true'
        run: 'echo "Version change found! Will run Release CI. New version: ${{ steps.check.outputs.version }} (${{ steps.check.outputs.type }})"'

      - name: Create Release
        if: steps.check.outputs.changed == 'true'
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{steps.check.outputs.version}}
          release_name: Release ${{steps.check.outputs.version}}
          draft: false
          prerelease: false
      
      - name: Build Docker Image
        if: steps.create_release.outcome == 'Success'
        uses: whoan/docker-build-with-cache-action@v5
        with:
          image_name: halvardssm/package-translation-fetch/translations
          dockerfile: .github/Dockerfile
          username: halvardssm
          password: "${{ secrets.GITHUB_TOKEN }}"
          registry: docker.pkg.github.com
          push_git_tag: true

      - name: Publish package to NPM
        if: steps.create_release.outcome == 'Success'
        run: docker run docker.pkg.github.com/halvardssm/package-translation-fetch/translations echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" >> ~/.npmrc && yarn publish --non-interactive