name: Translation Fetch CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: whoan/docker-build-with-cache-action@v5
        with:
          image_name: translations
          dockerfile: .github/Dockerfile

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: whoan/docker-build-with-cache-action@v5
        with:
          image_name: translations
          dockerfile: .github/Dockerfile

      - name: ESLint check
        run: docker run translations yarn test -p ${{ secrets.PATH }} -r ${{ secrets.REPO }} -t ${{ secrets.TOKEN }}

  publish:
    needs: test
    runs-on: ubuntu-latest
    if: contains(github.ref, 'master')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check version changes
        uses: EndBug/version-check@v1
        id: check
        with:
          diff-search: true

      - name: Version update detected
        if: steps.check.outputs.changed == 'true'
        run: 'echo "Version change found! New version: ${{ steps.check.outputs.version }} (${{ steps.check.outputs.type }})"'

      - uses: whoan/docker-build-with-cache-action@v5
        if: steps.check.outputs.changed == 'true'
        with:
          image_name: translations
          dockerfile: .github/Dockerfile

      - name: Publish package to NPM
        if: steps.check.outputs.changed == 'true'
        run: docker run translations yarn publish 
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
