name: Translation Fetch CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker Image
        uses: whoan/docker-build-with-cache-action@v5
        with:
          image_name: package-translation-fetch/translations
          dockerfile: .github/Dockerfile
          username: halvardssm
          password: "${{ secrets.GITHUB_TOKEN }}"
          registry: docker.pkg.github.com

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker Image
        uses: whoan/docker-build-with-cache-action@v5
        with:
          image_name: package-translation-fetch/translations
          dockerfile: .github/Dockerfile
          username: halvardssm
          password: "${{ secrets.GITHUB_TOKEN }}"
          registry: docker.pkg.github.com

      - name: Run Tests
        run: docker run translations yarn test -p ${{ secrets.PATH }} -r ${{ secrets.REPO }} -t ${{ secrets.TOKEN }}

  publish:
    needs: test
    runs-on: ubuntu-latest
    if: contains(github.ref, 'master')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check version changes
        uses: EndBug/version-check@v1
        id: check
        with:
          diff-search: true

      - name: Version update detected
        if: steps.check.outputs.changed == 'true'
        run: 'echo "Version change found! New version: ${{ steps.check.outputs.version }} (${{ steps.check.outputs.type }})"'

      - name: Build Docker Image
        uses: whoan/docker-build-with-cache-action@v5
        if: steps.check.outputs.changed == 'true'
        with:
          image_name: package-translation-fetch/translations
          dockerfile: .github/Dockerfile
          username: halvardssm
          password: "${{ secrets.GITHUB_TOKEN }}"
          registry: docker.pkg.github.com
          
      - name: Publish package to NPM
        if: steps.check.outputs.changed == 'true'
        run: docker run -e NODE_AUTH_TOKEN=${{ secrets.NPM_TOKEN }} translations yarn publish 
