name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test_node:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Tests
        run: yarn test -p ${{ secrets.PATH }} -r ${{ secrets.REPO }} -t ${{ secrets.TOKEN }}

  release_npm:
    needs: test_node
    runs-on: ubuntu-latest
    if: contains(github.ref, 'main')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check version changes
        id: check
        uses: EndBug/version-check@v2.0.1
        with:
          diff-search: true
          file-name: ./node/package.json

      - name: Version update detected
        if: steps.check.outputs.changed == 'true'
        run: 'echo "Version change found! Will run Release CI. New version: ${{ steps.check.outputs.version }} (${{ steps.check.outputs.type }})"'

      - name: Create Release
        if: steps.check.outputs.changed == 'true'
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{steps.check.outputs.version}}
          release_name: Release ${{steps.check.outputs.version}}
          draft: false
          prerelease: false

      - name: Publish package to NPM
        if: steps.create_release.outcome == 'Success'
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" >> ~/.npmrc && yarn pack && yarn publish translation-fetch-v${{steps.check.outputs.version}}.tgz --non-interactive
